[package]
name = "day11"
version = "0.1.0"
authors = ["Lauri Kurki <lauri.kurki@siili.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.aoc-utils]
path = "../aoc-utils"

[dependencies]
itertools = "0.9.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "simulation"
harness = false